# Generated by Django 5.1.2 on 2024-10-26 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="image",
            new_name="image_url",
        ),
    ]
