# Generated by Django 5.1.1 on 2024-09-27 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date_ttime_of_publication",
            new_name="date_time_of_publication",
        ),
    ]
