# Generated by Django 5.1.1 on 2024-10-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0002_rename_date_ttime_of_publication_comment_date_time_of_publication",
        ),
        ("photos", "0002_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_time_of_publication"]},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["date_time_of_publication"],
                name="common_comm_date_ti_d3f02d_idx",
            ),
        ),
    ]
