# Generated by Django 5.1.1 on 2024-10-23 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
    ]
