# Generated by Django 5.1.1 on 2024-10-14 08:26

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="",
                validators=[petstagram.photos.validators.FileSizeValidator(5)],
            ),
        ),
    ]
