# Generated by Django 5.1.2 on 2024-10-27 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_url",
            new_name="post_image_url",
        ),
    ]
