# Generated by Django 5.1.2 on 2024-10-27 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="image_url",
            new_name="profile_image_url",
        ),
    ]
