# Generated by Django 5.1.2 on 2024-10-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_rename_image_url_post_post_image_url"),
        ("profiles", "0002_rename_image_url_author_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="profiles.author",
            ),
        ),
    ]
