# Generated by Django 5.1.1 on 2024-09-27 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_alter_pet_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="personal_photo",
            new_name="personal_pet_photo",
        ),
    ]
