# Generated by Django 5.1.1 on 2024-10-13 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_rename_personal_pet_photo_pet_personal_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="personal_photo",
            new_name="personal_pet_photo",
        ),
    ]
