# Generated by Django 5.1.2 on 2024-10-24 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=30, unique=True)),
                ("artist", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop MusicPop Music", "Pop"),
                            ("Jazz MusicJazz Music", "Jazz"),
                            ("R&B MusicR&B Music", "Rnb"),
                            ("Rock MusicRock Music", "Rock"),
                            ("Country MusicCountry Music", "Country"),
                            ("Dance MusicDance Music", "Dance"),
                            ("Hip Hop MusicHip Hop Music", "Hiphop"),
                            ("OtherOther", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
