# Generated by Django 5.1.1 on 2024-10-01 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="PostModel",
        ),
    ]
