# Generated by Django 5.1.1 on 2024-10-02 08:38

import forumApp.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_rename_post_postmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="content",
            field=models.TextField(
                validators=[forumApp.posts.validators.BadLanguageValidator()]
            ),
        ),
    ]
