# Generated by Django 5.1.1 on 2024-10-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_commentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
