# Generated by Django 5.1.1 on 2024-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_commentmodel_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
